/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlLibro;
import javax.swing.JOptionPane;
import modelo.RegistroLibro;

/**
 *
 * @author Prado
 */
public class GUILibro extends javax.swing.JFrame {

    /**
     * Creates new form GUISibdi
     */
    
   private controlador.ControlLibro controlador; 
   
   public GUILibro(RegistroLibro registroLibro) {
        initComponents();
        controlador=new ControlLibro(panelDataLibro,panelBotones,registroLibro,this);
        panelBotones.escuchar(controlador);
        panelDataLibro.escucharBuscar(controlador);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataLibro1 = new vista.PanelDataLibro();
        panelBotones1 = new vista.PanelBotones();
        panelDataLibro = new vista.PanelDataLibro();
        panelBotones = new vista.PanelBotones();

        panelDataLibro1.setBorder(null);
        panelDataLibro1.setForeground(new java.awt.Color(51, 255, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDataLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDataLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotones panelBotones;
    private vista.PanelBotones panelBotones1;
    private vista.PanelDataLibro panelDataLibro;
    private vista.PanelDataLibro panelDataLibro1;
    // End of variables declaration//GEN-END:variables

public static void mensaje(String mensaje){
    
    JOptionPane.showMessageDialog(null, mensaje);

}//fin del metodo



}//fin de la clase
