/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlSIBDI;
import java.awt.event.ActionListener;

/**
 *
 * @author Prado
 */
public class GUISiBDI extends javax.swing.JFrame {

    /**
     * Creates new form GUISiBDI
     */
    public GUISiBDI() {
        super("Ventana SIBDI");
        initComponents();
        setLocationRelativeTo(null);
        ControlSIBDI control=new ControlSIBDI();
        escucharMenu(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        barraMenu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        registro = new javax.swing.JMenu();
        jmiLibro = new javax.swing.JMenuItem();
        mtnEstudiante = new javax.swing.JMenuItem();
        jmiPrestamos = new javax.swing.JMenuItem();
        jmiDevoluciones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivo.setText("Archivo");

        jmiSalir.setText("Salir");
        archivo.add(jmiSalir);

        barraMenu.add(archivo);

        registro.setText("Registros");

        jmiLibro.setText("Libros");
        registro.add(jmiLibro);

        mtnEstudiante.setText("Estudiante");
        registro.add(mtnEstudiante);

        jmiPrestamos.setText("Prestamos");
        registro.add(jmiPrestamos);

        jmiDevoluciones.setText("Devoluciones");
        registro.add(jmiDevoluciones);

        barraMenu.add(registro);

        jMenu5.setText("jMenu5");
        barraMenu.add(jMenu5);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISiBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISiBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISiBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISiBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISiBDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiDevoluciones;
    private javax.swing.JMenuItem jmiLibro;
    private javax.swing.JMenuItem jmiPrestamos;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem mtnEstudiante;
    private javax.swing.JMenu registro;
    // End of variables declaration//GEN-END:variables

    
    public void escucharMenu(ActionListener control){
    
    this.jmiDevoluciones.addActionListener(control);
    this.jmiLibro.addActionListener(control);
    this.mtnEstudiante.addActionListener(control);
    this.jmiPrestamos.addActionListener(control);
    this.jmiSalir.addActionListener(control);
    
    }//fin del metodo
    
    public static final String MENU_SALIR="Salir";
    public static final String MENU_LIBRO="Libros";
    public static final String MENU_ESTUDIANTE="Estudiante";
    public static final String MENU_PRESTAMOS="Prestamos";
    public static final String MENU_DEVOLUCIONES="Devoluciones";

}//fin de la clase
